{% set name = "mdsapt" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/calpolyccg/MDSAPT/archive/v{{ version }}.tar.gz
  sha256: 8d5892f8205a1eb63b6a8f336e75bc79b4948f23a1ae98db6f4986b3f1ce9c71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mdsapt = mdsapt.cli:cli

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - psi4 =>1.9.1
    - mdanalysis >=2.7.0
    - rdkit >=2023.09.5
    - openmm >=8.1.1
    - pdbfixer >=1.9
    - numpy
    - click
    - pandas
    - pyarrow # needed for pandas
    - pyyaml

test:
  source_files:
    - mdsapt
  requires:
    - pip
    - pytest
    - nglview
    - notebook
  commands:
    - pip check
    - pytest -p no:warnings -vvv mdsapt

about:
  home: https://github.com/calpolyccg/MDSAPT
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL3
  summary: SAPT Calculations for MDAnalysis
  doc_url: https://mdsapt.readthedocs.io/
  dev_url: https://github.com/calpolyccg/MDSAPT

extra:
  recipe-maintainers:
   - ALescoulie
   - ifd3f
